name: saladtri
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  gradient_widgets: ^0.4.1
  smooth_star_rating: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/landing_background.png
  - images/cloud.png
  - images/logo.png
  - images/logo_group.png
  - images/logo_white.png
  - images/background_bezier_one.png
  - images/background_bezier_two.png
  - images/background_bezier_three.png
  - images/background_bezier_four.png
  - images/background_bezier_five.png
  - images/background_recipe_detail.png
  - images/icons/username.png
  - images/icons/password.png
  - images/icons/email.png
  - images/recipes/popular_first.png
  - images/recipes/popular_second.png
  - images/recipes/best_first.png
  - images/recipes/best_second.png
  - images/recipes/best_third.png
  - images/recipes/cat_first.png
  - images/recipes/cat_second.png
  - images/recipes/cat_third.png
  - images/ingredients/ing_first.png
  - images/ingredients/ing_second.png
  - images/ingredients/ing_third.png
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FormIcon
      fonts:
        - asset: fonts/FormIcon.ttf
    - family: FavoriteIcon
      fonts:
        - asset: fonts/FavoriteIcon.ttf
    - family: Quantify
      fonts:
        - asset: fonts/Quantify.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
